In [1]:
import numpy as np

In [ ]:
# OR GATE PERCEPTRON

In [2]:
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
target_output = np.array([[0,1,1,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
weights = np.array([[.1],[.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [6]:
bias = 0.3
lr = 0.05

In [7]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [8]:
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [13]:
for epoch in range(25000):
    inputs = input_features
    
    # Feedforward input
    in_o = np.dot(inputs, weights) + bias
    
    # Feedforward output
    out_o = sigmoid(in_o)
    
    # Backprop & Calc Error
    error = out_o - target_output
    
    x = error.sum()
    print(x)
    
    # Calc derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)
    
    # Mult individual derivatives
    deriv = derror_douto * douto_dino
    
    # Find transpose of input features
    inputs = input_features.T
    deriv_final = np.dot(inputs,deriv)
    
    # Update Weights
    weights -= lr * deriv_final
    
    # Updating bias weight value
    for i in deriv:
        bias -= lr * i
    

-0.00014372531672921657
-0.00014376965092570415
-0.00014381396418583492
-0.00014385825651991313
-0.00014390252793784752
-0.00014394677844929704
-0.00014399100806453818
-0.0001440352167926054
-0.0001440794046445662
-0.00014412357162933015
-0.0001441677177577566
-0.0001442118430388592
-0.0001442559474823385
-0.0001443000310991302
-0.0001443440938982063
-0.00014438813588955185
-0.0001444321570829507
-0.0001444761574890957
-0.00014452013711668127
-0.00014456409597597697
-0.00014460803407687767
-0.0001446519514292366
-0.00014469584804283064
-0.00014473972392706203
-0.00014478357909237377
-0.0001448274135482791
-0.000144871227304659
-0.0001449150203709504
-0.00014495879275737422
-0.0001450025444734021
-0.00014504627552924115
-0.00014508998593404376
-0.00014513367569780194
-0.00014517734483039668
-0.00014522099334165345
-0.00014526462124090506
-0.00014530822853860148
-0.00014535181524401308
-0.00014539538136659758
-0.00014543892691622207
-0.00014548245190303816
-0.00014552595633644805
-0.0001

In [14]:
print(weights)
print(bias)

[[9.56988705]
 [9.56991131]]
[-4.44214573]


In [21]:
# Inputs
single_point = np.array([1,0])

# Step 1
result1 = np.dot(single_point, weights) + bias

# Step 2
result2 = sigmoid(result1)

print(result2)

# Added code to round up
r2 = result2
if r2 >= .5:
    r2 = 1
else:
    r2 = 0
print(r2)

[0.99410502]
1


In [20]:
single_point = np.array([0,0])

result1 = np.dot(single_point, weights) + bias

result2 = sigmoid(result1)

print(result2)

# Added code to round up
r2 = result2
if r2 >= .5:
    r2 = 1
else:
    r2 = 0
print(r2)

[0.01163372]
0


In [22]:
# Now make an AND GATE FROM SCRATCH!

In [33]:
# And gate truth table input
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])

# And gate truth table output
target_output = np.array([[0,0,0,1]])
target_output = target_output.reshape(4,1) # You could always just add more brackets

weights = np.array([[.1],[.2]])

for epoch in range(50000):
    inputs = input_features
    
    # Feedforward input
    in_o = np.dot(inputs, weights) + bias
    
    # Feedforward output
    out_o = sigmoid(in_o)
    
    # Backprop & Calc Error
    error = out_o - target_output
    
    x = error.sum()
    print(x)
    
    # Calc derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)
    
    # Mult individual derivatives
    deriv = derror_douto * douto_dino
    
    # Find transpose of input features
    inputs = input_featuresA.T
    deriv_final = np.dot(inputs,deriv)
    
    # Update Weights
    weights -= lr * deriv_final
    
    # Updating bias weight value
    for i in deriv:
        bias -= lr * i

-0.9999642905847147
-0.9999633509539901
-0.9999623836822124
-0.9999613878910716
-0.9999603626728097
-0.9999593070891948
-0.9999582201704582
-0.9999571009141945
-0.9999559482842212
-0.9999547612093972
-0.9999535385824009
-0.999952279258462
-0.999950982054049
-0.9999496457455093
-0.9999482690676602
-0.9999468507123297
-0.9999453893268437
-0.99994388351246
-0.999942331822745
-0.9999407327618913
-0.9999390847829764
-0.9999373862861566
-0.9999356356167963
-0.9999338310635303
-0.9999319708562546
-0.9999300531640464
-0.9999280760930064
-0.9999260376840253
-0.9999239359104676
-0.9999217686757716
-0.9999195338109639
-0.9999172290720814
-0.9999148521375006
-0.9999124006051716
-0.9999098719897475
-0.9999072637196138
-0.9999045731338067
-0.9999017974788204
-0.9998989339052985
-0.9998959794646034
-0.9998929311052625
-0.9998897856692834
-0.9998865398883354
-0.9998831903797916
-0.9998797336426264
-0.9998761660531633
-0.9998724838606674
-0.9998686831827766
-0.9998647600007663
-0.9998607101546414
-0.99

In [34]:
print(weights)
print(bias)

[[9.23909842]
 [9.23909991]]
[-14.14687293]


In [35]:
# Inputs
single_point = np.array([1,0])

# Step 1
result1 = np.dot(single_point, weights) + bias

# Step 2
result2 = sigmoid(result1)

print(result2)

# Added code to round up
r2 = result2
if r2 >= .5:
    r2 = 1
else:
    r2 = 0
print(r2)

[0.00733472]
0


In [36]:
# Inputs
single_point = np.array([1,1])

# Step 1
result1 = np.dot(single_point, weights) + bias

# Step 2
result2 = sigmoid(result1)

print(result2)

# Added code to round up
r2 = result2
if r2 >= .5:
    r2 = 1
else:
    r2 = 0
print(r2)

[0.98702057]
1


In [ ]:
# This is a simple model that can not do non linear data
# In my next project I'll try to build multi layer neural networks!